name: 'Mike Larson '
favicon: null
layout_spectrum: 0.24697658163495362
typography_spectrum: 0.8375070146284997
title: Editorial Culinary Lifestyle Photographer
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#72401f'
    - '#f18500'
    - '#cbc2b1'
    - '#fbd305'
  brandStrength: 0
  lightness: 0.6603470966219902
  saturation: 0.9413809410762042
  rhythmicContrast: 0.18612389964982867
purpose: []
